### ISSUE TITLE
Clean call object missing

### ISSUE THREAD

**Issue by pinunQ** [r-lib/cleancall#23]
While running call_with_cleanup function -- 

Error states cleancall_call shows error as no object with 'cleancall_call' not found! 

It doesn't seemed to have happened before and my version is newest since downloaded through Github itself

**Comment by gaborcsardi** [comment]
Can you show your code?

**Comment by gaborcsardi** [comment]
I am going to close this for lack of details, but please reopen with more info if you still have issues.
